class Themes {
  static definitions = {
    // Existing themes
    default: { accent: '#f42365', name: 'Pink' },
    pink: { accent: '#f42365', name: 'Pink' },
    blue: { accent: '#2563eb', name: 'Blue' },
    purple: { accent: '#9333ea', name: 'Purple' },
    green: { accent: '#059669', name: 'Green' },
    orange: { accent: '#ea580c', name: 'Orange' },
    red: { accent: '#dc2626', name: 'Red' },
    cyan: { accent: '#0891b2', name: 'Cyan' },
    yellow: { accent: '#ca8a04', name: 'Yellow' },
    indigo: { accent: '#4338ca', name: 'Indigo' },
    emerald: { accent: '#10b981', name: 'Emerald' },
    rose: { accent: '#e11d48', name: 'Rose' },
    violet: { accent: '#7c3aed', name: 'Violet' },
    amber: { accent: '#f59e0b', name: 'Amber' },
    teal: { accent: '#0d9488', name: 'Teal' },
    lime: { accent: '#65a30d', name: 'Lime' },
    fuchsia: { accent: '#c026d3', name: 'Fuchsia' },

    // New themes
    slate: { accent: '#6b7280', name: 'Slate' },
    gray: { accent: '#6b7280', name: 'Gray' },
    neutral: { accent: '#4b5563', name: 'Neutral' },
    sky: { accent: '#6366f1', name: 'Sky' },
    indigo: { accent: '#4338ca', name: 'Indigo' },
    violet: { accent: '#7c3aed', name: 'Violet' },
    purple: { accent: '#9333ea', name: 'Purple' },
    pink: { accent: '#f42365', name: 'Pink' },
    rose: { accent: '#e11d48', name: 'Rose' },
    red: { accent: '#dc2626', name: 'Red' },
    orange: { accent: '#ea580c', name: 'Orange' },
    amber: { accent: '#f59e0b', name: 'Amber' },
    yellow: { accent: '#ca8a04', name: 'Yellow' },
    lime: { accent: '#65a30d', name: 'Lime' },
    green: { accent: '#059669', name: 'Green' },
    emerald: { accent: '#10b981', name: 'Emerald' },
    teal: { accent: '#0d9488', name: 'Teal' },
    cyan: { accent: '#0891b2', name: 'Cyan' },
    blue: { accent: '#2563eb', name: 'Blue' },
    indigo: { accent: '#4338ca', name: 'Indigo' },
    violet: { accent: '#7c3aed', name: 'Violet' },
    purple: { accent: '#9333ea', name: 'Purple' },
    pink: { accent: '#f42365', name: 'Pink' },
    rose: { accent: '#e11d48', name: 'Rose' },
    red: { accent: '#dc2626', name: 'Red' },
    orange: { accent: '#ea580c', name: 'Orange' },
    amber: { accent: '#f59e0b', name: 'Amber' },
    yellow: { accent: '#ca8a04', name: 'Yellow' },
    lime: { accent: '#65a30d', name: 'Lime' },
    green: { accent: '#059669', name: 'Green' },
    emerald: { accent: '#10b981', name: 'Emerald' },
    teal: { accent: '#0d9488', name: 'Teal' },
    cyan: { accent: '#0891b2', name: 'Cyan' },
    sky: { accent: '#6366f1', name: 'Sky' },
    blue: { accent: '#2563eb', name: 'Blue' },
    mango: { accent: '#FFD700', name: 'Mango' },
    saffron: { accent: '#FFB84D', name: 'Saffron' },
    tangerine: { accent: '#FF8000', name: 'Tangerine' },
    burntOrange: { accent: '#CC6600', name: 'Burnt Orange' },
    forestGreen: { accent: '#228B22', name: 'Forest Green' },
    coral: { accent: '#FF7F50', name: 'Coral' },
    maroon: { accent: '#800000', name: 'Maroon' },
    azure: { accent: '#007FFF', name: 'Azure' },
    mauve: { accent: '#E0B0FF', name: 'Mauve' },
    sage: { accent: '#8FBC8F', name: 'Sage' },
    orchid: { accent: '#EE82EE', name: 'Orchid' },
    lapis: { accent: '#3A86FF', name: 'Lapis' },
    amethyst: { accent: '#9370DB', name: 'Amethyst' },
    violetCrimson: { accent: '#8E44AD', name: 'Violet Crimson' },
    turquoise: { accent: '#00CED1', name: 'Turquoise' },
    indigoVibe: { accent: '#4B0082', name: 'Indigo Vibe' },
    neonMagenta: { accent: '#FF00FF', name: 'Neon Magenta' },
    electricBlue: { accent: '#00FFFF', name: 'Electric Blue' },
    neonGreen: { accent: '#00FF00', name: 'Neon Green' },
    cyberPink: { accent: '#FF1493', name: 'Cyber Pink' },
    retroPurple: { accent: '#800080', name: 'Retro Purple' },
    neonYellow: { accent: '#FFFF00', name: 'Neon Yellow' }
  };
}